export const SET_SEARCHED_WORDS = 'SET_SEARCHED_WORDS';
export const ADD_WORD = 'ADD_WORD';
export const KEY_PRESSED = "KEY_PRESSED";
export const EVAL_CORRECT = "EVAL_CORRECT";
export const EVAL_INCORRECT = "EVAL_INCORRECT";
